[config]
reload_apps = false

[templates]

[templates.hyprland]
input_path = "/home/grey/.config/matugen/templates/hyprland.conf"
output_path = "/home/grey/.config/hypr/colors.conf"

# [templates.hyprlock]
# input_path = "/home/grey/.config/matugen/templates/hyprlock.conf"
# output_path = "/home/grey/.config/hypr/hyprlock.conf"

[templates.kitty]
input_path = "/home/grey/.config/matugen/templates/kitty.conf"
output_path = "/home/grey/.config/kitty/colors.conf"

[templates.rofi]
input_path = "/home/grey/.config/matugen/templates/rofi.rasi"
output_path = "/home/grey/.config/rofi/colors.rasi"

[templates.swaync]
input_path = "/home/grey/.config/matugen/templates/swaync.css"
output_path = "/home/grey/.config/swaync/style.css"

[templates.waybar_colors]
input_path = "/home/grey/.config/matugen/templates/waybar-colors.css"
output_path = "/home/grey/.config/waybar/colors.css"

# Gtk3
[templates.gtk3]
input_path = '/home/grey/.config/matugen/templates/gtk-colors.css'
output_path = '/home/grey/.config//gtk-3.0/gtk.css'

# Gtk4
[templates.gtk4]
input_path = '/home/grey/.config/matugen/templates/gtk-colors.css'
output_path = '/home/grey/.config/gtk-4.0/gtk.css'


[templates.cava]
input_path = '/home/grey/.config/matugen/templates/cava-colors.ini'
output_path = '/home/grey/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.btop]
input_path = '/home/grey/.config/matugen/templates/btop.theme'
output_path = '/home/grey/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'
